[cerebrium.deployment]
name = "6-deepseek-sglang"
python_version = "3.11"
docker_base_image_url = "debian:bookworm-slim"
disable_auth = false
include = ['./*', 'main.py', 'cerebrium.toml']
exclude = ['.*']
pre_build_commands = [
    "pip install sglang[all]>=0.4.2.post2 --find-links https://flashinfer.ai/whl/cu124/torch2.5/flashinfer"
]

[cerebrium.hardware]
cpu = 4
memory = 12.0
compute = "AMPERE_A10"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 30
replica_concurrency = 1
response_grace_period = 1800
scaling_metric = "concurrency_utilization"
scaling_target = 100

[cerebrium.dependencies.pip]
huggingface_hub = "latest"
pydantic = "latest"