[cerebrium.deployment]
name = "11-ultravox"
python_version = "3.11"
docker_base_image_url = "debian:bookworm-slim"
disable_auth = false
include = ['./*', 'main.py', 'cerebrium.toml']
exclude = ['.*']

[cerebrium.runtime.custom]
port = 8765
entrypoint = ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8765"]
healthcheck_endpoint = "/health"

[cerebrium.hardware]
cpu = 4
memory = 16.0
compute = "AMPERE_A10"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 90
replica_concurrency = 1
response_grace_period = 900
scaling_metric = "concurrency_utilization"
scaling_target = 80
scaling_buffer= 1

[cerebrium.dependencies.pip]
transformers = "latest"
peft = "latest"
librosa = "latest"
"huggingface-hub[hf-transfer]" = "latest"
vllm = "latest"
pyaudio = "latest"
pydantic-settings = "latest"
textual = "latest"
loguru = "latest"
"pipecat-ai[cartesia,daily,silero,ultravox]" = "0.0.67"
fastapi = "latest"
uvicorn = "latest"

[cerebrium.dependencies.apt]
ffmpeg = "latest"
libportaudio2 = "latest"
portaudio19-dev = "latest"
