[cerebrium.deployment]
name = "20-openai-compatible-vllm"
python_version = "3.11"

include = "[./*, main.py, cerebrium.toml]"
exclude = "[.*]"
shell_commands = []

[cerebrium.hardware]
cpu = 3
memory = 14.0
gpu = "AMPERE_A10"
gpu_count = 1
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
cooldown = 20

[cerebrium.dependencies.pip]
vllm = "latest"