[cerebrium.deployment]
name = "5-live-translation-room"
python_version = "3.11"
docker_base_image_url = "debian:bookworm-slim"
disable_auth = false
include = ['./*', 'main.py', 'cerebrium.toml']
exclude = ['.*']

[cerebrium.hardware]
cpu = 4
memory = 18.0
compute = "ADA_L40"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 90
replica_concurrency = 1
response_grace_period = 900
scaling_metric = "concurrency_utilization"
scaling_target = 100

[cerebrium.dependencies.pip]
transformers = "latest"
peft = "latest"
librosa = "latest"
"huggingface-hub[hf-transfer]" = "latest"
vllm = "latest"
cartesia = "latest"
"daily-python" = "latest"
"silero_vad" = "latest"

[cerebrium.dependencies.apt]
ffmpeg = "latest"