services:
  orpheus-fastapi:
    container_name: orpheus-fastapi
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
      - "5005:5005"
    env_file:
      - .env
    environment:
      - ORPHEUS_API_URL=http://llama-cpp-server:5006/v1/completions
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    depends_on:
      llama-cpp-server:
        condition: service_started

  llama-cpp-server:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    ports:
      - "5006:5006"
    volumes:
      - ./models:/models
    env_file:
      - .env
    depends_on:
      model-init:
        condition: service_completed_successfully
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    command: >
      -m /models/${ORPHEUS_MODEL_NAME}
      --port ${LLAMA_ARG_PORT:-5006}
      --host ${LLAMA_ARG_HOST:-0.0.0.0}
      --n-gpu-layers ${LLAMA_ARG_N_GPU_LAYERS:-120}
       
      --ctx-size ${ORPHEUS_MAX_TOKENS}
      --n-predict ${ORPHEUS_MAX_TOKENS}
      --rope-scaling linear
      ${LLAMA_ARG_NO_CONTEXT_SHIFT:+--no-context-shift}
      ${LLAMA_ARG_SPECIAL:+--special}
      ${LLAMA_ARG_NO_WARMUP:+--no-warmup}
      ${LLAMA_ARG_SPM_INFILL:+--spm-infill}
      --pooling ${LLAMA_ARG_POOLING:-none}
      ${LLAMA_ARG_CONT_BATCHING:+--cont-batching}
      ${LLAMA_ARG_NO_CONT_BATCHING:+--no-cont-batching}
      ${LLAMA_ARG_NO_WEBUI:+--no-webui}
      ${LLAMA_ARG_EMBEDDINGS:+--embeddings}
      ${LLAMA_ARG_RERANKING:+--reranking}
      --timeout ${LLAMA_ARG_TIMEOUT:-600}
      --threads-http ${LLAMA_ARG_THREADS_HTTP:-1}
      --cache-reuse ${LLAMA_ARG_CACHE_REUSE:-0}

  model-init:
    image: curlimages/curl:latest
    user: ${UID}:${GID}
    volumes:
      - ./models:/app/models
    working_dir: /app
    command: >
      sh -c '
      if [ ! -f /app/models/${ORPHEUS_MODEL_NAME} ]; then
        echo "Downloading model file..."
        wget -P /app/models https://huggingface.co/lex-au/${ORPHEUS_MODEL_NAME}/resolve/main/${ORPHEUS_MODEL_NAME}
      else
        echo "Model file already exists"
      fi'
    restart: "no"
