version: "3.9"

services:
  orpheus-fastapi:
    container_name: orpheus-fastapi
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
      - "5005:5005"
    env_file:
      - .env
    environment:
      - ORPHEUS_API_URL=http://llama-cpp-server:5006/v1/completions
      - CUDA_VISIBLE_DEVICES=0
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: '8gb'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    depends_on:
      llama-cpp-server:
        condition: service_started

  llama-cpp-server:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    container_name: llama-cpp-server
    ports:
      - "5006:5006"
    volumes:
      - ./models:/models
    env_file:
      - .env
    environment:
      # Force use of cuBLAS for faster matmuls
      - GGML_CUDA_FORCE_CUBLAS=1
      - CUDA_VISIBLE_DEVICES=0
      - GGML_CUDA_FORCE_MMQ=1
      - GGML_CUDA_DMMV_X=32
      - GGML_CUDA_MMV_Y=32
      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: '16gb'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    command: >
      -m /models/${ORPHEUS_MODEL_NAME}
      --host ${LLAMA_ARG_HOST:-0.0.0.0}
      --port ${LLAMA_ARG_PORT:-5006}
      --n-gpu-layers 99                     
      --threads 4                           
      --threads-batch 4                      
      --batch-size 16                         
      --ubatch-size 16                 
      --ctx-size 8192
      --cont-batching
      --timeout 100
      --mlock
      --flash-attn
      --parallel 32
      --threads-http 2 
      --no-mmap
      --tensor-split 0
                       

  model-init:
    image: curlimages/curl:latest
    user: ${UID}:${GID}
    volumes:
      - ./models:/app/models
    working_dir: /app
    command: >
      sh -c '
      if [ ! -f /app/models/${ORPHEUS_MODEL_NAME} ]; then
        echo "Downloading model file..."
        wget -P /app/models https://huggingface.co/lex-au/${ORPHEUS_MODEL_NAME}/resolve/main/${ORPHEUS_MODEL_NAME}
      else
        echo "Model file already exists"
      fi'
    restart: "no"
