[cerebrium.deployment]
name = "27-ecommerce-live-stream"
python_version = "3.10"
docker_base_image_url = "nvidia/cuda:12.1.1-runtime-ubuntu22.04"
include = ["main.py", "cerebrium.toml", "detection.py", "best.pt"]
exclude = [".*"]

[cerebrium.hardware]
cpu = 3
memory = 16.0
compute = "AMPERE_A10"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 30

[cerebrium.dependencies.pip]
torch = "latest"
torchvision = "latest"
onnx = "latest"
onnxruntime = "latest"
pycocotools = "latest"
PyYAML = "latest"
scipy = "latest"
onnxslim = "latest"
onnxruntime-gpu = "latest"
gradio = "latest"
opencv-python = "latest"
psutil = "latest"
py-cpuinfo = "latest"
huggingface-hub = "latest"
safetensors = "0.4.4"
daily-python = "latest"
pillow = "latest"
einops = "latest"
transformers = "latest"
supabase = "latest"
libsql_experimental = "latest"
"google-search-results" = "latest"
"ultralytics" = "latest"

[cerebrium.dependencies.apt]
git = "latest"
"libgl1-mesa-glx" = "latest"
"ibglib2.0-0" = "latest"