[cerebrium.deployment]
name = "5-streaming-endpoint"
python_version = "3.12"
include = ["./*", "main.py", "cerebrium.toml"]
exclude = [".*"]
shell_commands = []
docker_base_image_url = "nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04"

[cerebrium.hardware]
cpu = 4
memory = 14.0
compute = "AMPERE_A10"
gpu_count = 1
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
cooldown = 10

[cerebrium.dependencies.pip]
"git+https://github.com/huggingface/peft.git" = "latest"
"git+https://github.com/huggingface/transformers.git" = "latest"
"git+https://github.com/huggingface/accelerate.git" = "latest"
bitsandbytes = "latest"
sentencepiece = "latest"
torch = "latest"
pydantic = "latest"

[cerebrium.dependencies.apt]
git = "latest"