[cerebrium.deployment]
name = "persistent-storage-management"
python_version = "3.11"

include = "[./*, main.py, cerebrium.toml]"
exclude = "[.*]"
shell_commands = []

[cerebrium.hardware]
cpu = 1
memory = 4.0
gpu = "AMPERE_A10"
gpu_count = 0
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
cooldown = 20

[cerebrium.dependencies.pip]
vllm = "latest"