[cerebrium.deployment]
name = "2-gradio-interface"
python_version = "3.12"
include = ['./*', 'main.py', 'cerebrium.toml']
exclude = ['.*']
disable_auth = true

[cerebrium.runtime.custom]
entrypoint = ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
port = 8080
healthcheck_endpoint = "/health"

[cerebrium.hardware]
cpu = 2
memory = 4.0
compute = "CPU"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 1
cooldown = 30
replica_concurrency = 1000

[cerebrium.dependencies.pip]
gradio = "latest"
fastapi = "latest"
requests = "latest"
httpx = "latest"
uvicorn = "latest"
starlette = "latest"

