[cerebrium.deployment]
name = "tensorrt-triton-demo"
python_version = "3.12"
disable_auth = true
deployment_initialization_timeout = 830
include = ["./*", "cerebrium.toml"]
exclude = [".*"]

[cerebrium.hardware]
cpu = 8.0
memory = 60.0
compute = "ADA_L40"
gpu_count = 1
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 30
replica_concurrency = 128
scaling_metric = "concurrency_utilization"

[cerebrium.dependencies.pip]
huggingface_hub = "latest"
transformers = "latest"

[cerebrium.runtime.custom]
port = 8000
healthcheck_endpoint = "/v2/health/live"
readycheck_endpoint = "/v2/health/ready"
dockerfile_path = "./Dockerfile"

[cerebrium.experimental]
checkpointing = true
