[cerebrium.deployment]
name = "grpc-server"
python_version = "3.12"
include = ["./*", "main.py", "cerebrium.toml", "*"]
exclude = [".*"]
shell_commands = [""]

[cerebrium.hardware]
cpu = 1
memory = 1
compute = "CPU"
gpu_count = 0
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 1
max_replicas = 2
cooldown = 1
replica_concurrency = 100

[cerebrium.dependencies.pip]
grpcio = "1.71.0"
protobuf = "6.30.1"