[cerebrium.deployment]
name = "1-websockets"
python_version = "3.12"
disable_auth = true
include = ["*"]
exclude = [".*"]
shell_commands = []

[cerebrium.runtime.custom]
port = 5555
entrypoint = ["fastapi", "run", "main.py", "--port", "5555"]
healthcheck_endpoint = "/health"

[cerebrium.hardware]
cpu = 0.25
memory = 0.1
compute = "CPU"
gpu_count = 1
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
replica_concurrency = 10
response_grace_period = 3600
cooldown = 1800

[cerebrium.dependencies.pip]
loguru = "latest"
"fastapi[standard]" = "latest"
