[cerebrium.deployment]
name = "1-websockets"
python_version = "3.12"
disable_auth = true
include = ["*"]
exclude = [".*"]
shell_commands = []

[cerebrium.runtime.custom]
port = 5000
entrypoint = ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
healthcheck_endpoint = "/health"

[cerebrium.hardware]
cpu = 0.5
memory = 0.5
compute = "CPU"
gpu_count = 1
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
replica_concurrency = 10
response_grace_period = 3600
cooldown = 1800

[cerebrium.dependencies.pip]
loguru = "latest"
fastapi = "latest"
"uvicorn[standard]" = "latest"