[cerebrium.deployment]
name = "5-dockerfile"
python_version = "3.12"
include = ["./*"]
exclude = [".*"]
shell_commands = [""]

[cerebrium.hardware]
cpu = 1
memory = 1.0
compute = "CPU"
gpu_count = 0

[cerebrium.runtime.custom]
port = 8192
healthcheck_endpoint = "/health"
readycheck_endpoint = "/ready"
dockerfile_path = "./Dockerfile"

[cerebrium.scaling]
min_replicas = 5
max_replicas = 5
cooldown = 1
replica_concurrency = 1
