[cerebrium.deployment]
name = "12-realtime-livekit"
python_version = "3.11"
docker_base_image_url = "debian:bookworm-slim"
disable_auth = false
include = ['./*', 'main.py', 'cerebrium.toml']
exclude = ['.*']
shell_commands = ["python main.py download-files"]

[cerebrium.hardware]
cpu = 2.0
memory = 12.0
compute = "CPU"

[cerebrium.scaling]
min_replicas = 1
max_replicas = 5
cooldown = 30
replica_concurrency = 1
response_grace_period = 900
scaling_metric = "concurrency_utilization"
scaling_target = 100
scaling_buffer = 0
roll_out_duration_seconds = 0

[cerebrium.dependencies.pip]
"livekit-agents[deepgram,openai,cartesia,rime,silero,turn-detector]" = "latest"
"livekit-plugins-noise-cancellation" = "~=0.2"
"python-dotenv" = "latest"
"fastapi" = "latest"
"uvicorn" = "latest"

[cerebrium.runtime.custom]
port = 8600
entrypoint = ["python", "main.py", "dev"]