[cerebrium.deployment]
name = "wandb-sweep"
python_version = "3.11"
docker_base_image_url = "debian:bookworm-slim"
disable_auth = false
include = ['./*', 'main.py', 'cerebrium.toml']
exclude = ['.*']

[cerebrium.hardware]
cpu = 6
memory = 30.0
compute = "ADA_L40"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 30
replica_concurrency = 1
response_grace_period = 3600
scaling_metric = "concurrency_utilization"
scaling_target = 100

[cerebrium.dependencies.paths]
pip = "requirements.txt"