[cerebrium.deployment]
name = "2-using-cerebrium-secrets"
python_version = "3.12"
include = "[./*, main.py, cerebrium.toml]"
exclude = "[.*]"
shell_commands = []

[cerebrium.hardware]
cpu = 3
memory = 14.0
gpu = "AMPERE_A10"
gpu_count = 1
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 10

[cerebrium.dependencies.pip]
"git+https://github.com/huggingface/peft.git" = "latest"
"git+https://github.com/huggingface/transformers.git" = "latest"
"git+https://github.com/huggingface/accelerate.git" = "latest"
bitsandbytes = "latest"
evaluate = "latest"
numpy = "latest"
sentencepiece = "latest"
datasets = "latest"
torch = "latest"
scipy = "latest"

[cerebrium.dependencies.apt]
git = "latest"
