[cerebrium.deployment]
name = "4-coaching-training"
python_version = "3.11"
docker_base_image_url="debian:bookworm-slim"
include = ["./*", "main.py", "cerebrium.toml"]
exclude = ["videos", "rag"]
shell_commands = []

[cerebrium.hardware]
cpu = 2
memory = 6.0
compute = "CPU"
gpu_count = 0
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 120
replica_concurrency = 100

[cerebrium.dependencies.pip]
mistralai = "latest"
requests = "latest"