[cerebrium.deployment]
name = "snapshot-qwen-vl-sglang"
python_version = "3.11"
docker_base_image_url = "nvidia/cuda:12.8.0-devel-ubuntu22.04"
disable_auth = true
include = ['./*', 'main.py', 'cerebrium.toml']
exclude = ['.*']
deployment_initialization_timeout = 830  # Cerebrium max.

[cerebrium.hardware]
cpu = 10.0
memory = 60.0
compute = "ADA_L40"
region = "us-east-1"
provider = "aws"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
cooldown = 30
replica_concurrency = 1
scaling_metric = "concurrency_utilization"

[cerebrium.build]
use_uv = true

[cerebrium.dependencies.pip]
transformers = "latest"
huggingface_hub = "latest"
hf_transfer = "latest"
pillow = "latest"
requests = "latest"
torch = "2.8.0"
"sglang[all]" = "0.5.5"

[cerebrium.dependencies.apt]
libnuma-dev = "latest"
libgomp1 = "latest"
ninja-build = "latest"
python3-dev = "latest"

[cerebrium.experimental]
checkpointing = true