[cerebrium.deployment]
name = "6-multi-gpu-inference"
python_version = "3.12"
include = "[./*, main.py, cerebrium.toml]"
exclude = "[.*]"
shell_commands = []

[cerebrium.hardware]
cpu = 4
memory = 30.0
gpu = "AMPERE_A10"
gpu_count = 4
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
cooldown = 10

[cerebrium.dependencies.pip]
ray = "latest"
transformers = "latest"
bitsandbytes = "latest"
peft = "latest"
torch = "latest"
numpy = "latest"
pydantic = "latest"
huggingface_hub = "latest"
safetensors = "latest"
accelerate = "latest"
scipy = "latest"
sentencepiece = "latest"
hf_transfer = "latest"
optimum = "latest"

[cerebrium.dependencies.apt]