[cerebrium.deployment]
name = "5-xtts"
python_version = "3.11"
docker_base_image_url = "nvidia/cuda:12.1.1-runtime-ubuntu22.04"
include = ["./*", "main.py", "cerebrium.toml"]
exclude = [".*"]

[cerebrium.hardware]
cpu = 2
memory = 12.0
compute = "AMPERE_A10"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 30

[cerebrium.dependencies.pip]
TTS = "latest"