[cerebrium.deployment]
name = "5-loading-model-weights-faster"
python_version = "3.12"
include = "[./*, main.py, fast_load.py, cerebrium.toml]"
exclude = "[.*]"
shell_commands = []
base_image = "nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04"

[cerebrium.hardware]
cpu = 4
memory = 30.0
gpu = "AMPERE_A10"
gpu_count = 1
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 10

[cerebrium.dependencies.pip]
torch = "latest"
numpy = "latest"
accelerate = "latest"
diffusers = "latest"
ftfy = "latest"
scipy = "latest"
"bitsandbytes[gpu]" = "latest"
transformers = "latest"
tensorizer = "latest"
huggingface_hub = "latest"

[cerebrium.dependencies.apt]
git = "latest"