[cerebrium.deployment]
name = "11-whisper-transcription"
python_version = "3.12"
include = "[./*, main.py, util.py, cerebrium.toml]"
exclude = "[.*]"
shell_commands = []

[cerebrium.hardware]
cpu = 4
memory = 14.0
compute = "AMPERE_A10"
gpu_count = 1
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
cooldown = 10

[cerebrium.dependencies.pip]
transformers = "latest"
accelerate = "latest"
openai-whisper = "latest"

[cerebrium.dependencies.apt]