[cerebrium.deployment]
name = "32-websockets"
python_version = "3.12"
include = ["*"]
exclude = [".*"]
shell_commands = []

[cerebrium.runtime.custom]
port = 5000
entrypoint = ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000"]
healthcheck_endpoint = "/health"

[cerebrium.hardware]
cpu = 2
memory = 8.0
compute = "CPU"
gpu_count = 1
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
cooldown = 10
replica_concurrency = 1

[cerebrium.dependencies.pip]
loguru = "latest"
fastapi = "latest"
"uvicorn[standard]" = "latest"