[cerebrium.deployment]
name = "17-orpheus-fastapi"
python_version = "3.11"
docker_base_image_url = "debian:bookworm-slim"
disable_auth = true
include = ['./*', 'main.py', 'cerebrium.toml']
exclude = ['.*']

[cerebrium.hardware]
cpu = 4.0
memory = 6.0
compute = "CPU"
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
cooldown = 30
replica_concurrency = 100
scaling_metric = "concurrency_utilization"

[cerebrium.runtime.custom]
port = 5005
entrypoint = ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5005"]


[cerebrium.dependencies.paths]
pip = "requirements.txt"

[cerebrium.dependencies.apt]
libportaudio2 = "latest"